### ISSUE TITLE
agentv bash not working with cygwin

### ISSUE THREAD

**Issue by bmaggi** [PrismTech/agentv#1] opened 2016-02-23 10:13 UTC
I tried to launch ./agentv test test in a cygwin console and got the following exception

```
Exception in thread "main" java.lang.ClassNotFoundException: Could not find class com.prismtech.agentv.runtime.DDSRuntime
        at com.prismtech.agentv.RepositoryClassLoader.findClass(RepositoryClassLoader.scala:69)
        at com.prismtech.agentv.RepositoryClassLoader.loadClass(RepositoryClassLoader.scala:34)
        at com.prismtech.agentv.RepositoryClassLoader.loadClass(RepositoryClassLoader.scala:20)
        at com.prismtech.agentv.Launcher$.main(Launcher.scala:18)
        at com.prismtech.agentv.Launcher.main(Launcher.scala)

```

I also tried a direct call to the library : `java -Dddsi.network.interface=eth3 -cp ../lib/agentv-assembly-0.5.0-SNAPSHOT.jar com.prismtech.agentv.Launcher com.prismtech.agentv.runtime.DDSRuntime repository com.prismtech.cafe.core.ServiceEnvironmentImpl fakeid fakeinfo 0` but got the same exception

Is there a way to activate the debug mode to get more information?

**Comment by kydos** [comment] 2016-02-23 10:43
@bmaggi, do you see any info logs from the Repository listing the jars it has discovered? The exception is being raised since the class could not be resolved but the RepositoryClassLoader.  

This may be due to the fact that the Repository initialisation is non-blocking, meaning that depending on your filesystem (but this would be surprising) the class is trying to be loaded before the Repository has finished opening the jar files present in the "repository" directory. 

I don't have a cygwin environment at hand currently, but will be able to try this on cygwin this early PM. 
Will let you know what I find out. 

What you could do meanwhile is to comment the line:

`scalacOptions ++=  Seq("-Xelide-below", "INFO")`

From the `build.sbt` file and do:

`sbt assembly`

to create an agentv assembly that does not elide any kind of logging.

A+

**Comment by kydos** [comment] 2016-02-23 10:50
@bmaggi one more thing, did you see any info log of the kind:

```
[Repository | Log]:  Opening Jar = ./repository/agentv-assembly-0.5.0-SNAPSHOT.jar 
[Repository | Log]:  Opening Jar = ./repository/agentv-core-types_2.11-0.5.0-SNAPSHOT.jar 
[Repository | Log]:  Opening Jar = ./repository/agentv-microsvc-hello_2.11-0.5.0-SNAPSHOT.jar 
[Repository | Log]:  Opening Jar = ./repository/agentv-runtime-assembly-0.5.0-SNAPSHOT.jar 
```

If you don't see that, I'd guess that the problem is definitively a `repository` path problem. Thus try to provide the fully qualified path.

HTH.

**Comment by kydos** [comment] 2016-02-23 10:58
@bmaggi, I've just made a commit that makes the Repository initialisation synchronous. This means that if you continue to see the issue with the class loading it is a problem with the path that is being specified. 

Can you please do a pull of the repository and run again the agent? 

Let me know what happens!

A+

**Comment by bmaggi** [comment] 2016-02-23 12:30
@kydos : Just pulled your last commit still the same problem.
Here is the full log : 

```
 [Repository | Log]:  Opening Jar = ./repository\agentv-assembly-0.5.0-SNAPSHOT.jar
 [Repository | Log]:  Opening Jar = ./repository\agentv-commander-assembly-0.5.0-SNAPSHOT.jar
 [Repository | Log]:  Opening Jar = ./repository\agentv-core-types_2.11-0.5.0-SNAPSHOT.jar
 [Repository | Log]:  Opening Jar = ./repository\agentv-microsvc-daytimelog_2.11-0.5.0-SNAPSHOT.jar
 [Repository | Log]:  Opening Jar = ./repository\agentv-microsvc-daytime_2.11-0.5.0-SNAPSHOT.jar
 [Repository | Log]:  Opening Jar = ./repository\agentv-microsvc-hello_2.11-0.5.0-SNAPSHOT.jar
 [Repository | Log]:  Opening Jar = ./repository\agentv-microsvc_2.11-0.5.0-SNAPSHOT.jar
 [Repository | Log]:  Opening Jar = ./repository\agentv-prelude_2.11-0.5.0-SNAPSHOT.jar
 [Repository | Log]:  Opening Jar = ./repository\agentv-runtime-assembly-0.5.0-SNAPSHOT.jar
 [Repository | Warning]:  Class com\prismtech\agentv\runtime\DDSRuntime.class Not found
Exception in thread "main" java.lang.ClassNotFoundException: Could not find class com.prismtech.agentv.runtime.DDSRuntime
        at com.prismtech.agentv.RepositoryClassLoader.findClass(RepositoryClassLoader.scala:69)
        at com.prismtech.agentv.RepositoryClassLoader.loadClass(RepositoryClassLoader.scala:34)
        at com.prismtech.agentv.RepositoryClassLoader.loadClass(RepositoryClassLoader.scala:20)
        at com.prismtech.agentv.Launcher$.main(Launcher.scala:17)
        at com.prismtech.agentv.Launcher.main(Launcher.scala)

```

I will try to recompile without the logger option.

**Comment by bmaggi** [comment] 2016-02-23 12:41
Same problem after recompiltation.

I tried to launch it derectly in the windows command line, using this command:

`java -Dddsi.network.interface=eth3 -cp ../lib/agentv-assembly-0.5.0-SNAPSHOT.jar com.prismtech.agentv.Launcher com.prismtech.agentv.runtime.DDSRuntime repository com.prismtech.cafe.core.ServiceEnvironmentImpl fakeid fakeinfo 0
`

I got the following log:
`←[32m [Repository | Log]:  Opening Jar = repository\agentv-assembly-0.5.0-SNAPSH
OT.jar ←[0m
←[32m [Repository | Log]:  Opening Jar = repository\agentv-commander-assembly-0.
5.0-SNAPSHOT.jar ←[0m
←[32m [Repository | Log]:  Opening Jar = repository\agentv-core-types_2.11-0.5.0
-SNAPSHOT.jar ←[0m
←[32m [Repository | Log]:  Opening Jar = repository\agentv-microsvc-daytimelog_2
.11-0.5.0-SNAPSHOT.jar ←[0m
←[32m [Repository | Log]:  Opening Jar = repository\agentv-microsvc-daytime_2.11
-0.5.0-SNAPSHOT.jar ←[0m
←[32m [Repository | Log]:  Opening Jar = repository\agentv-microsvc-hello_2.11-0
.5.0-SNAPSHOT.jar ←[0m
←[32m [Repository | Log]:  Opening Jar = repository\agentv-microsvc_2.11-0.5.0-S
NAPSHOT.jar ←[0m
←[32m [Repository | Log]:  Opening Jar = repository\agentv-prelude_2.11-0.5.0-SN
APSHOT.jar ←[0m
←[32m [Repository | Log]:  Opening Jar = repository\agentv-runtime-assembly-0.5.
0-SNAPSHOT.jar ←[0m
←[43m [Repository | Warning]:  Class com\prismtech\agentv\runtime\DDSRuntime.cla
ss Not found ←[0m
Exception in thread "main" java.lang.ClassNotFoundException: Could not find clas
s com.prismtech.agentv.runtime.DDSRuntime
        at com.prismtech.agentv.RepositoryClassLoader.findClass(RepositoryClassL
oader.scala:69)
        at com.prismtech.agentv.RepositoryClassLoader.loadClass(RepositoryClassL
oader.scala:34)
        at com.prismtech.agentv.RepositoryClassLoader.loadClass(RepositoryClassL
oader.scala:20)
        at com.prismtech.agentv.Launcher$.main(Launcher.scala:17)
        at com.prismtech.agentv.Launcher.main(Launcher.scala)`

**Comment by bmaggi** [comment] 2016-02-23 12:51
For information, I'm using:

```
Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_2
0).
```

**Comment by kydos** [comment] 2016-02-23 13:26
@bmaggi, the problem is now fixed. Thanks for pointing it out.   Tt was due to the use of File.separator to represent class name path on Windows. Actually "/" has to be used regardless of the target OS.

Pull the latest version of the repo. Everything should work now (I did verify on Cygwin).

A+

**Closed as completed by kydos** 2016-02-23 13:26 UTC

**Comment by bmaggi** [comment] 2016-02-23 13:46
@kydos : Thx. I confirm, it's working now.
